# web:
#   build: .
#   environment:
#     MYENV: EXAMPLE
#   volumes:
#     - .:/code
# web_migrate:
#   extends:
#     service: web
#   command: python manage.py migrate
# web_run:
#   extends:
#     service: web
#   command: python manage.py runserver 127.0.0.1:8000
#   ports:
#     - "8000:8000"

version: "3.8"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db