# Generated by Django 2.2.10 on 2021-07-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multiple_answers',
            field=models.ManyToManyField(to='quiz_api.Choice'),
        ),
    ]
