# Generated by Django 2.2.10 on 2021-07-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_auto_20210728_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text answer', 'text'), ('one answer', 'one'), ('multiple answer', 'multiple')], max_length=80),
        ),
    ]
